### PR TITLE
Ifix fiscal change.

### PR DESCRIPTION
**Pull request by lakshmisravani-wtt-egov**

### CODE REVIEW

**Review by rushang7 — CHANGES_REQUESTED** [review]
I have advised not set this value above 100. So I will not approve this PR.

**Comment by rushang7** [comment]
As this is in QA, are you doing it just to try out or are you planning to promote the same in Prod.?

**Comment by lakshmisravani-wtt-egov** [comment]
> As this is in QA, are you doing it just to try out or are you planning to promote the same in Prod.?

It's not planned to give to Prod directly, We have given this no for testing purpose only, once it tested will make the change back to 100 or 10.

**Review by rushang7 — APPROVED** [review]
Approving just for testing purposes.

**Review by pintu-eGov — APPROVED** [review]

**Pull request merged**
